/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shortest_path_3;

import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author AnhTu
 */
public class App extends javax.swing.JFrame {
    private final String STR_ALL = "Tất cả";
    private final int MST = 0;
    private final int SPT = 1;
    private final String [] MST_PROBLEMS = {"Prim", "Kruskal"};
    private final String [] SPT_PROBLEMS = {"Dijkstra", "Ford-Bellman"};
    
    
    
    GraphPanel gp;
    int problem;
    int algorithm;
    /*
    problem = 0:
        algorithm = 0: Prim
        algorithm = 1: Kruskal
    problem = 1:
        algorithm = 0: Dijkstra
        algorithm = 1: Ford-Bellman
    
    */
    
    public App() {
        initComponents();
        this.setTitle("Graph Algorithms Demo");
        gp = new GraphPanel();
        gp.taOut = this.taOutput;
        gp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 3, true));
        gp.setSize(graphPanel_App.getWidth(), graphPanel_App.getHeight());
        graphPanel_App.add(gp);
        //txtFilePath.setMaximumSize(new Dimension(153, 27));
        setEnabledComponents(false);
        problem = MST;
        cbAlgorithm.setModel(new DefaultComboBoxModel<>(MST_PROBLEMS));
        algorithm = 0;
        setToolTip();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTravelGraph = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        optionPanel = new javax.swing.JPanel();
        btRun = new javax.swing.JButton();
        btRunStep = new javax.swing.JButton();
        cbSourceNode = new javax.swing.JComboBox<>();
        cbAlgorithm = new javax.swing.JComboBox<>();
        btClearOutput = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btTraversal = new javax.swing.JButton();
        btTraversalStep = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btRefresh = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cbProblem = new javax.swing.JComboBox<>();
        cbDestNode = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        graphPanel_App = new javax.swing.JPanel();
        outputPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miRandomGraph = new javax.swing.JMenuItem();
        miOpenGraph = new javax.swing.JMenuItem();
        miSaveGraph = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        optionPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 3, true));

        btRun.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btRun.setText("Chạy");
        btRun.setToolTipText("Chạy đê!");
        btRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRunActionPerformed(evt);
            }
        });

        btRunStep.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btRunStep.setText("Chạy từng bước");
        btRunStep.setToolTipText("");
        btRunStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRunStepActionPerformed(evt);
            }
        });

        cbSourceNode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cbSourceNode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSourceNodeItemStateChanged(evt);
            }
        });

        cbAlgorithm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- None -" }));
        cbAlgorithm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAlgorithmmItemStateChanged(evt);
            }
        });

        btClearOutput.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btClearOutput.setText("Xóa output");
        btClearOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearOutputActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("Chọn các node nguồn và đích");

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Problem");

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel7.setText("Node nguồn");

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel8.setText("Node đích");

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setText("Duyệt đồ thị");

        groupTravelGraph.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("DFS");
        jRadioButton1.setToolTipText("Duyệt theo chiều sâu");

        groupTravelGraph.add(jRadioButton2);
        jRadioButton2.setText("BFS");
        jRadioButton2.setToolTipText("Duyệt theo chiều rộng");
        jRadioButton2.setEnabled(false);

        btTraversal.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btTraversal.setText("Duyệt");
        btTraversal.setToolTipText("Duyệt đồ thị từ node 1");
        btTraversal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTraversalActionPerformed(evt);
            }
        });

        btTraversalStep.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btTraversalStep.setText("Duyệt từng bước");
        btTraversalStep.setToolTipText("Duyệt đồ thị từng bước từ node 1");
        btTraversalStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTraversalStepActionPerformed(evt);
            }
        });

        btRefresh.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btRefresh.setText("Refresh");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 255));
        jLabel11.setText("Mô phỏng ");

        cbProblem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MST", "SPT" }));
        cbProblem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProblemItemStateChanged(evt);
            }
        });

        cbDestNode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "1", "2", "3" }));
        cbDestNode.setToolTipText("Nếu node đích = node nguồn thì duyệt tất cả");
        cbDestNode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDestNodeItemStateChanged(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 255));
        jLabel12.setText("Thuật toán");

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setText("(Bài toán MST không cần chọn)");

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addComponent(cbProblem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                        .addComponent(cbSourceNode, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(22, 22, 22))
                            .addComponent(cbDestNode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                        .addComponent(btRun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRunStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(optionPanelLayout.createSequentialGroup()
                                .addComponent(btRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btClearOutput))
                            .addComponent(jLabel5)
                            .addGroup(optionPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel12))
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addGroup(optionPanelLayout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton2))
                            .addComponent(jLabel9)
                            .addGroup(optionPanelLayout.createSequentialGroup()
                                .addComponent(btTraversal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btTraversalStep)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(5, 5, 5)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSourceNode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDestNode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProblem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRun, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRunStep, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTraversal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTraversalStep, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClearOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        graphPanel_App.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 3));
        graphPanel_App.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                graphPanel_AppComponentResized(evt);
            }
        });

        javax.swing.GroupLayout graphPanel_AppLayout = new javax.swing.GroupLayout(graphPanel_App);
        graphPanel_App.setLayout(graphPanel_AppLayout);
        graphPanel_AppLayout.setHorizontalGroup(
            graphPanel_AppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        graphPanel_AppLayout.setVerticalGroup(
            graphPanel_AppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        outputPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 3));

        taOutput.setEditable(false);
        taOutput.setColumns(20);
        taOutput.setRows(5);
        jScrollPane1.setViewportView(taOutput);

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 255));
        jLabel10.setText("Output");

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputPanelLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");

        miRandomGraph.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        miRandomGraph.setText("Đồ thị ngẫu nhiên");
        miRandomGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRandomGraphActionPerformed(evt);
            }
        });
        jMenu1.add(miRandomGraph);

        miOpenGraph.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miOpenGraph.setText("Mở đồ thị");
        miOpenGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpenGraphActionPerformed(evt);
            }
        });
        jMenu1.add(miOpenGraph);

        miSaveGraph.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miSaveGraph.setText("Lưu đồ thị");
        miSaveGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaveGraphActionPerformed(evt);
            }
        });
        jMenu1.add(miSaveGraph);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("About the author");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphPanel_App, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(graphPanel_App, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void btRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRunActionPerformed
        //gp.repaint();   //Để xóa lần chạy trước đi
        if(problem == MST) {
            if(algorithm == 0) {
                // Prim
                gp.paintPrim();
            } else if(algorithm == 1) {
                // Kruskal
                JOptionPane.showMessageDialog(this, "Chức năng này sẽ được phát trong phiên bản tiếp theo", "OMG! Chức năng này hay đấy, nhưng chưa tồn tại", JOptionPane.INFORMATION_MESSAGE);
            }
        } else if(problem == SPT) { 
            if(algorithm == 0) {
                // Dijkstra
                gp.paintDijkstra();
            } else if(algorithm == 1) {
                // Ford-Bellman
                JOptionPane.showMessageDialog(this, "Chức năng này sẽ được phát trong phiên bản tiếp theo", "OMG! Chức năng này hay đấy, nhưng chưa tồn tại", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btRunActionPerformed

    private void btRunStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRunStepActionPerformed
        setupWhileRunningStep(false);
        
        if(problem == MST) {
            if(algorithm == 0) {
                // Prim
                //JOptionPane.showMessageDialog(this, "Chức năng này sẽ được phát trong phiên bản tiếp theo", "OMG! Chức năng này hay đấy, nhưng chưa tồn tại", JOptionPane.INFORMATION_MESSAGE);
                gp.paintPrimSteps();
            } else if(algorithm == 1) {
                // Kruskal
                JOptionPane.showMessageDialog(this, "Chức năng này sẽ được phát trong phiên bản tiếp theo", "OMG! Chức năng này hay đấy, nhưng chưa tồn tại", JOptionPane.INFORMATION_MESSAGE);
            }
        } else if(problem == SPT) { 
            if(algorithm == 0) {
                // Dijkstra
                gp.paintDijkstraSteps();
            } else if(algorithm == 1) {
                // Ford-Bellman
                JOptionPane.showMessageDialog(this, "Chức năng này sẽ được phát trong phiên bản tiếp theo", "OMG! Chức năng này hay đấy, nhưng chưa tồn tại", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
        
        if(!gp.isRunningStep) {
            setupWhileRunningStep(true);
        }
    }//GEN-LAST:event_btRunStepActionPerformed

    private void graphPanel_AppComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_graphPanel_AppComponentResized
        gp.setSize(graphPanel_App.getWidth(), graphPanel_App.getHeight());
    }//GEN-LAST:event_graphPanel_AppComponentResized

    private void btClearOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearOutputActionPerformed
        taOutput.setText("");
    }//GEN-LAST:event_btClearOutputActionPerformed

    private void cbSourceNodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSourceNodeItemStateChanged
        gp.setSourceNode(cbSourceNode.getSelectedIndex() + 1);
    }//GEN-LAST:event_cbSourceNodeItemStateChanged

    private void cbAlgorithmmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAlgorithmmItemStateChanged
        algorithm = cbAlgorithm.getSelectedIndex();
        System.out.println("problem = " + problem + ", algorithm = "+algorithm);
        setToolTip();
    }//GEN-LAST:event_cbAlgorithmmItemStateChanged

    private void setToolTip() {
        if(problem == 0) {
            btRun.setToolTipText("Chạy thuật toán " + MST_PROBLEMS[algorithm]);
        } else if(problem == 1) {
            btRun.setToolTipText("Chạy thuật toán " + SPT_PROBLEMS[algorithm]);
        }
    }
    
    private void btTraversalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTraversalActionPerformed
        gp.traversalDFS(1);
    }//GEN-LAST:event_btTraversalActionPerformed

    private void btTraversalStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTraversalStepActionPerformed
        setupWhileTravelsalStep(false);
        gp.traversalDFSSteps(1);    //tạm thời cứ duyệt từ node 1
        if(!gp.isRunningStep) {
            setupWhileTravelsalStep(true);
        }
    }//GEN-LAST:event_btTraversalStepActionPerformed

    private void miSaveGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaveGraphActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Text file", "txt"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("pdf file", "pdf"));
        
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String filePath = String.valueOf(fileChooser.getSelectedFile()); //str là đường dẫn tới file, ví dụ:  C:\Users\AnhTu\Documents\image for java project\bejeweled3.png.  chú ý dấu \ chứ ko phải /
            if(!filePath.endsWith(".txt")) filePath += ".txt";
            gp.saveGraph(filePath);
        }
    }//GEN-LAST:event_miSaveGraphActionPerformed

    private void miOpenGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpenGraphActionPerformed
        new OpenGraphFrame(this).setVisible(true);
    }//GEN-LAST:event_miOpenGraphActionPerformed

    private void miRandomGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRandomGraphActionPerformed
        Random rd = new Random();
        int n = rd.nextInt(11) + 5;
        int s = rd.nextInt(n) + 1;
        int t = rd.nextInt(n) + 1;
        while(t == s) {
            t = rd.nextInt(n) + 1;
        }
        
        gp.randomGraph(n, s, t);     //ngẫu nhiên từ 5 - 15 node
        gp.repaint();
        setComboBoxData();
        setEnabledComponents(true);
    }//GEN-LAST:event_miRandomGraphActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, new MessageWithLink("Thanks for using my app.\nThis app was created by ATT. Visit <a style=\"text-decoration: none; color: blue;\" href=\"https://github.com/AnhtuTa/NetbeansProjects/tree/master/ShortestPathRouting\">my Github</a> to download source code"), "About", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        gp.repaint();
        System.out.println("problem = " + problem + ", algorithm = " + algorithm);
    }//GEN-LAST:event_btRefreshActionPerformed

    private void cbProblemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProblemItemStateChanged
        problem = cbProblem.getSelectedIndex();
        setDataCbAlgo();
        algorithm = 0;
        setToolTip();
    }//GEN-LAST:event_cbProblemItemStateChanged

    private void cbDestNodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDestNodeItemStateChanged
        gp.setDestNode(cbDestNode.getSelectedIndex());
    }//GEN-LAST:event_cbDestNodeItemStateChanged

    public void setComboBoxData() {
        int nodeQuantities = gp.nodeQuantity;
        
        String [] str = new String [nodeQuantities];
        String [] str2 = new String [nodeQuantities+1];
        str2[0] = STR_ALL;
        for (int i = 0; i < nodeQuantities; i++) {
            str[i] = (i+1) + "";
            str2[i+1] = (i+1) + "";
        }
        cbSourceNode.setModel(new DefaultComboBoxModel<>(str));
        cbDestNode.setModel(new DefaultComboBoxModel<>(str2));
        cbSourceNode.setSelectedIndex(gp.getSourceNode() - 1);
        cbDestNode.setSelectedIndex(gp.getDestNode());      //Do cbDestNode có phần tử đầu tiên là "Tất cả"
    }
    
    // set data for cbAlgorithm
    private void setDataCbAlgo() {
        if(problem == MST) {
            cbAlgorithm.setModel(new DefaultComboBoxModel<>(MST_PROBLEMS));
        } else if(problem == SPT) {
            cbAlgorithm.setModel(new DefaultComboBoxModel<>(SPT_PROBLEMS));
        }
    }
    
    public void setEnabledComponents(boolean b) {
        cbSourceNode.setEnabled(b);
        cbDestNode.setEnabled(b);
        btRun.setEnabled(b);
        btRunStep.setEnabled(b);
        btTraversal.setEnabled(b);
        btTraversalStep.setEnabled(b);
        miSaveGraph.setEnabled(b);
        cbProblem.setEnabled(b);
        cbAlgorithm.setEnabled(b);
    }
    
    private void setupWhileRunningStep(boolean b) {
        cbSourceNode.setEnabled(b);
        cbDestNode.setEnabled(b);
        btRun.setEnabled(b);
        btTraversal.setEnabled(b);
        btTraversalStep.setEnabled(b);
        miSaveGraph.setEnabled(b);
        cbProblem.setEnabled(b);
        cbAlgorithm.setEnabled(b);
        btRefresh.setEnabled(b);
        btClearOutput.setEnabled(b);                
    }
    
    private void setupWhileTravelsalStep(boolean b) {
        cbSourceNode.setEnabled(b);
        cbDestNode.setEnabled(b);
        btRun.setEnabled(b);
        btRunStep.setEnabled(b);
        btTraversal.setEnabled(b);
        miSaveGraph.setEnabled(b);
        cbProblem.setEnabled(b);
        cbAlgorithm.setEnabled(b);
    }
    

    public JComboBox<String> getCbDestNode() {
        return cbDestNode;
    }

    public JComboBox<String> getCbSourceNode() {
        return cbSourceNode;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClearOutput;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btRun;
    private javax.swing.JButton btRunStep;
    private javax.swing.JButton btTraversal;
    private javax.swing.JButton btTraversalStep;
    private javax.swing.JComboBox<String> cbAlgorithm;
    private javax.swing.JComboBox<String> cbDestNode;
    private javax.swing.JComboBox<String> cbProblem;
    private javax.swing.JComboBox<String> cbSourceNode;
    private javax.swing.JPanel graphPanel_App;
    private javax.swing.ButtonGroup groupTravelGraph;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JMenuItem miOpenGraph;
    private javax.swing.JMenuItem miRandomGraph;
    private javax.swing.JMenuItem miSaveGraph;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JTextArea taOutput;
    // End of variables declaration//GEN-END:variables
}
