/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shortest_path_3;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author AnhTu
 */
public class OpenGraphFrame extends javax.swing.JFrame {

    App app;
    /**
     * Creates new form OpenGraphFrame
     */
    public OpenGraphFrame(App app) {
        this.app = app;
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(app);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtFilePath = new javax.swing.JTextField();
        btChoooseFile = new javax.swing.JButton();
        btOpenGraph = new javax.swing.JButton();
        btOpenGraph1 = new javax.swing.JButton();
        btHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("Mở đồ thị từ file");

        txtFilePath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btChoooseFile.setText("...");
        btChoooseFile.setToolTipText("Chọn file");
        btChoooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChoooseFileActionPerformed(evt);
            }
        });

        btOpenGraph.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btOpenGraph.setText("Mở");
        btOpenGraph.setToolTipText("Mở đồ thị đã chọn");
        btOpenGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenGraphActionPerformed(evt);
            }
        });

        btOpenGraph1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btOpenGraph1.setText("Cancel");
        btOpenGraph1.setToolTipText("Lấy đồ thị có sẵn từ file");
        btOpenGraph1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenGraph1ActionPerformed(evt);
            }
        });

        btHelp.setText("?");
        btHelp.setToolTipText("Help");
        btHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btOpenGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btOpenGraph1)
                                .addGap(4, 4, 4))
                            .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btChoooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btChoooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(btHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOpenGraph)
                    .addComponent(btOpenGraph1))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOpenGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenGraphActionPerformed
        String filePath = txtFilePath.getText();
        if(filePath.equals("")) {
            JOptionPane.showMessageDialog(this, "File ko được trống", "Lỗi!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean b = app.gp.readGraphFromFile(filePath, this);
        if(b == false) {
            return;
        }
        app.gp.repaint();
        app.setComboBoxData();
        app.setEnabledComponents(true);
        app.getCbSourceNode().setSelectedIndex(app.gp.getSourceNode() - 1);
        app.getCbDestNode().setSelectedIndex(app.gp.getDestNode());      //Do cbDestNode có phần tử đầu tiên là "Tất cả"
        this.dispose();
    }//GEN-LAST:event_btOpenGraphActionPerformed

    private void btChoooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChoooseFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Text file", "txt"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String filePath = String.valueOf(fileChooser.getSelectedFile()); //str là đường dẫn tới file, ví dụ:  C:\Users\AnhTu\Documents\image for java project\bejeweled3.png.  chú ý dấu \ chứ ko phải /
            txtFilePath.setText(filePath);
        }
    }//GEN-LAST:event_btChoooseFileActionPerformed

    private void btOpenGraph1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenGraph1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btOpenGraph1ActionPerformed

    private void btHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHelpActionPerformed
        StringBuilder builder = new StringBuilder("File chứa đồ thị phải có dạng sau\n");
        builder.append("Dòng thứ nhất chứa 3 số tương ứng với số lượng node n, node nguồn và node đích\n")
        .append("n dòng tiếp theo chứa ma trận trọng số nxn\n")
        .append("Sau đó dòng tiếp theo chứa 1 số flag\n")
        .append("flag = 1 thì n dòng tiếp theo nhập tọa độ của n node\n")
        .append("flag = 0 thì kết thúc nhập\n")
        .append("\nVí dụ:\n")
        .append("5 1 5\n" +
            "0 0 22 23 0 \n" +
            "0 0 22 13 15 \n" +
            "22 22 0 0 29 \n" +
            "23 13 0 0 0 \n" +
            "0 15 29 0 0 \n" +
            "1\n" +
            "273 85\n" +
            "162 296\n" +
            "162 137\n" +
            "308 300\n" +
            "86 342");
        JOptionPane.showMessageDialog(this, builder, "Cách tạo file đồ thị", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btHelpActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OpenGraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OpenGraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OpenGraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OpenGraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OpenGraphFrame(null).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChoooseFile;
    private javax.swing.JButton btHelp;
    private javax.swing.JButton btOpenGraph;
    private javax.swing.JButton btOpenGraph1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtFilePath;
    // End of variables declaration//GEN-END:variables
}
