/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Blob;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author tungt
 */
public class Phong extends javax.swing.JPanel {

    private BufferedImage image;
    int selectedComponent;

    /**
     * Creates new form Phong
     */
    public Phong() {
        initComponents();
        this.setSize(1100, 650);
        try {
            image = ImageIO.read(new File("D:\\Documents\\NetBeansProjects\\SDM\\rs\\room.png"));
        } catch (Exception e) {
        }
        reset();
    }

    void reset() {
        jLabel_name1.setText("Click để thêm sinh viên ");
        jLabel_name2.setText("Click để thêm sinh viên ");
        jLabel_name3.setText("Click để thêm sinh viên ");
        jLabel_name4.setText("Click để thêm sinh viên ");
        jLabel_name5.setText(" Click để thêm sinh viên");
        jLabel_name6.setText(" Click để thêm sinh viên");
        jLabel_name7.setText(" Click để thêm sinh viên");
        jLabel_name8.setText(" Click để thêm sinh viên");
        jLabel_image1.setIcon(null);
        jLabel_image2.setIcon(null);
        jLabel_image3.setIcon(null);
        jLabel_image4.setIcon(null);
        jLabel_image5.setIcon(null);
        jLabel_image6.setIcon(null);
        jLabel_image7.setIcon(null);
        jLabel_image8.setIcon(null);
    }

    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, 1100, 650, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_name1 = new javax.swing.JLabel();
        jLabel_image1 = new javax.swing.JLabel();
        jLabel_name2 = new javax.swing.JLabel();
        jLabel_image2 = new javax.swing.JLabel();
        jLabel_name3 = new javax.swing.JLabel();
        jLabel_image3 = new javax.swing.JLabel();
        jLabel_name4 = new javax.swing.JLabel();
        jLabel_image4 = new javax.swing.JLabel();
        jLabel_image5 = new javax.swing.JLabel();
        jLabel_name5 = new javax.swing.JLabel();
        jLabel_image6 = new javax.swing.JLabel();
        jLabel_name6 = new javax.swing.JLabel();
        jLabel_image7 = new javax.swing.JLabel();
        jLabel_name7 = new javax.swing.JLabel();
        jLabel_image8 = new javax.swing.JLabel();
        jLabel_name8 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel_b = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 650));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jLabel_name1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_name1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_name1.setOpaque(true);
        jLabel_name1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_name1MouseMoved(evt);
            }
        });
        jLabel_name1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_name1MousePressed(evt);
            }
        });

        jLabel_image1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_image1.setOpaque(true);

        jLabel_name2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_name2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_name2.setOpaque(true);
        jLabel_name2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_name2MouseMoved(evt);
            }
        });
        jLabel_name2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_name2MousePressed(evt);
            }
        });

        jLabel_image2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_image2.setOpaque(true);

        jLabel_name3.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_name3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_name3.setOpaque(true);
        jLabel_name3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_name3MouseMoved(evt);
            }
        });
        jLabel_name3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_name3MousePressed(evt);
            }
        });

        jLabel_image3.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_image3.setOpaque(true);

        jLabel_name4.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_name4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_name4.setOpaque(true);
        jLabel_name4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_name4MouseMoved(evt);
            }
        });
        jLabel_name4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_name4MousePressed(evt);
            }
        });

        jLabel_image4.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_image4.setOpaque(true);

        jLabel_image5.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_image5.setOpaque(true);

        jLabel_name5.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_name5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name5.setOpaque(true);
        jLabel_name5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_name5MouseMoved(evt);
            }
        });
        jLabel_name5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_name5MousePressed(evt);
            }
        });

        jLabel_image6.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_image6.setOpaque(true);

        jLabel_name6.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_name6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name6.setOpaque(true);
        jLabel_name6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_name6MouseMoved(evt);
            }
        });
        jLabel_name6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_name6MousePressed(evt);
            }
        });

        jLabel_image7.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_image7.setOpaque(true);

        jLabel_name7.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_name7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name7.setOpaque(true);
        jLabel_name7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_name7MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_name7MouseMoved(evt);
            }
        });
        jLabel_name7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_name7MousePressed(evt);
            }
        });

        jLabel_image8.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_image8.setOpaque(true);

        jLabel_name8.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_name8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name8.setOpaque(true);
        jLabel_name8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_name8MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_name8MouseMoved(evt);
            }
        });
        jLabel_name8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_name8MousePressed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/back.png"))); // NOI18N

        jLabel_b.setBackground(new java.awt.Color(0, 0, 153));
        jLabel_b.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_b.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_b.setText("B7");
        jLabel_b.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_name4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel_image4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel_image3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel_image2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_image1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_image5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_name5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_image6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_name6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_image7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_name7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_image8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_name8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel_b, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel_name1, jLabel_name2, jLabel_name3, jLabel_name4, jLabel_name5, jLabel_name6, jLabel_name7, jLabel_name8});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel_image1, jLabel_image2, jLabel_image3, jLabel_image4, jLabel_image5, jLabel_image6, jLabel_image7, jLabel_image8});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_image1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_image5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_name5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel_b, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_image2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_name6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_image6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_image3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_name7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_image7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_image4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_name4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_name8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_image8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel_image1, jLabel_image2, jLabel_image3, jLabel_image4, jLabel_image5, jLabel_image6, jLabel_image7, jLabel_image8});

    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_name1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name1MousePressed
        // TODO add your handling code here:

        this.selectedComponent = 1;
    }//GEN-LAST:event_jLabel_name1MousePressed

    private void jLabel_name2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name2MousePressed
        // TODO add your handling code here:

        this.selectedComponent = 2;
    }//GEN-LAST:event_jLabel_name2MousePressed

    private void jLabel_name3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name3MousePressed
        // TODO add your handling code here:

        this.selectedComponent = 3;
    }//GEN-LAST:event_jLabel_name3MousePressed

    private void jLabel_name4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name4MousePressed
        // TODO add your handling code here:

        this.selectedComponent = 4;
    }//GEN-LAST:event_jLabel_name4MousePressed

    private void jLabel_name5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name5MousePressed
        // TODO add your handling code here:

        this.selectedComponent = 5;
    }//GEN-LAST:event_jLabel_name5MousePressed

    private void jLabel_name6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name6MousePressed
        // TODO add your handling code here:

        this.selectedComponent = 6;
    }//GEN-LAST:event_jLabel_name6MousePressed

    private void jLabel_name7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name7MousePressed
        // TODO add your handling code here:

        this.selectedComponent = 7;
    }//GEN-LAST:event_jLabel_name7MousePressed

    private void jLabel_name8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name8MousePressed
        // TODO add your handling code here:
        this.selectedComponent = 8;
    }//GEN-LAST:event_jLabel_name8MousePressed

    private void jLabel_name1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name1MouseMoved
        // TODO add your handling code here:
        jLabel_name1.setBackground(new java.awt.Color(0, 0, 153));
    }//GEN-LAST:event_jLabel_name1MouseMoved

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged
    void resetBackGround() {

        jLabel_name1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel_name2.setBackground(new java.awt.Color(0, 0, 204));

        jLabel_name3.setBackground(new java.awt.Color(0, 0, 204));

        jLabel_name4.setBackground(new java.awt.Color(0, 0, 204));

        jLabel_name5.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_name6.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_name7.setBackground(new java.awt.Color(0, 0, 204));
        jLabel_name8.setBackground(new java.awt.Color(0, 0, 204));
    }
    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        resetBackGround();
    }//GEN-LAST:event_formMouseMoved

    private void jLabel_name2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name2MouseMoved
        // TODO add your handling code here:

        jLabel_name2.setBackground(new java.awt.Color(0, 0, 153));
    }//GEN-LAST:event_jLabel_name2MouseMoved

    private void jLabel_name3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name3MouseMoved
        // TODO add your handling code here:

        jLabel_name3.setBackground(new java.awt.Color(0, 0, 153));
    }//GEN-LAST:event_jLabel_name3MouseMoved

    private void jLabel_name4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name4MouseMoved
        // TODO add your handling code here:

        jLabel_name4.setBackground(new java.awt.Color(0, 0, 153));
    }//GEN-LAST:event_jLabel_name4MouseMoved

    private void jLabel_name5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name5MouseMoved
        // TODO add your handling code here:

        jLabel_name5.setBackground(new java.awt.Color(0, 0, 153));
    }//GEN-LAST:event_jLabel_name5MouseMoved

    private void jLabel_name6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name6MouseMoved
        // TODO add your handling code here:

        jLabel_name6.setBackground(new java.awt.Color(0, 0, 153));
    }//GEN-LAST:event_jLabel_name6MouseMoved

    private void jLabel_name7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name7MouseDragged
        // TODO add your handling code here:

        jLabel_name7.setBackground(new java.awt.Color(0, 0, 153));
    }//GEN-LAST:event_jLabel_name7MouseDragged

    private void jLabel_name8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name8MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_name8MouseDragged

    private void jLabel_name8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name8MouseMoved
        // TODO add your handling code here:

        jLabel_name8.setBackground(new java.awt.Color(0, 0, 153));
    }//GEN-LAST:event_jLabel_name8MouseMoved

    private void jLabel_name7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_name7MouseMoved
        // TODO add your handling code here:

        jLabel_name7.setBackground(new java.awt.Color(0, 0, 153));
    }//GEN-LAST:event_jLabel_name7MouseMoved
    public JLabel getBack() {
        return back;
    }

    public JLabel getComponent1() {
        return jLabel_name1;
    }

    public JLabel getComponent2() {
        return jLabel_name2;
    }

    public JLabel getComponent3() {
        return jLabel_name3;
    }

    public JLabel getComponent4() {
        return jLabel_name4;
    }

    public JLabel getComponent5() {
        return jLabel_name5;
    }

    public JLabel getComponent6() {
        return jLabel_name6;
    }

    public JLabel getComponent7() {
        return jLabel_name7;
    }

    public JLabel getComponent8() {
        return jLabel_name8;
    }

    void setImage(int i, Blob image) {
        
        try {
            byte[] temp = image.getBytes(1L, (int) image.length());
            ImageIcon ik = new ImageIcon(temp);
            Image igm = ik.getImage();
            Image newimg = igm.getScaledInstance(85, 92, Image.SCALE_REPLICATE);
            ik = new ImageIcon(newimg);
            if (i == 1) {
                jLabel_image1.setIcon(ik);
            }
            if (i == 2) {
                jLabel_image2.setIcon(ik);
            }
            if (i == 3) {
                jLabel_image3.setIcon(ik);
            }
            if (i == 4) {
                jLabel_image4.setIcon(ik);
            }
            if (i == 5) {
                jLabel_image5.setIcon(ik);
            }
            if (i == 6) {
                jLabel_image6.setIcon(ik);
            }
            if (i == 7) {
                jLabel_image7.setIcon(ik);
            }
            if (i == 8) {
                jLabel_image8.setIcon(ik);
            }

        } catch (SQLException ex) {
        }
    }

    public void setjLabel_name1(String name) {
        this.jLabel_name1.setText(name + " ");
    }

    public void setjLabel_name2(String name) {
        this.jLabel_name2.setText(name + " ");
    }

    public void setjLabel_name3(String name) {
        this.jLabel_name3.setText(name + " ");
    }

    public void setjLabel_name4(String name) {
        this.jLabel_name4.setText(name + " ");
    }

    public void setjLabel_name5(String name) {
        this.jLabel_name5.setText(" " + name);
    }

    public void setjLabel_name6(String name) {
        this.jLabel_name6.setText(" " + name);
    }

    public void setjLabel_name7(String name) {
        this.jLabel_name7.setText(" " + name);
    }

    public void setjLabel_name8(String name) {
        this.jLabel_name8.setText(" " + name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel_b;
    private javax.swing.JLabel jLabel_image1;
    private javax.swing.JLabel jLabel_image2;
    private javax.swing.JLabel jLabel_image3;
    private javax.swing.JLabel jLabel_image4;
    private javax.swing.JLabel jLabel_image5;
    private javax.swing.JLabel jLabel_image6;
    private javax.swing.JLabel jLabel_image7;
    private javax.swing.JLabel jLabel_image8;
    private javax.swing.JLabel jLabel_name1;
    private javax.swing.JLabel jLabel_name2;
    private javax.swing.JLabel jLabel_name3;
    private javax.swing.JLabel jLabel_name4;
    private javax.swing.JLabel jLabel_name5;
    private javax.swing.JLabel jLabel_name6;
    private javax.swing.JLabel jLabel_name7;
    private javax.swing.JLabel jLabel_name8;
    // End of variables declaration//GEN-END:variables
    
    void setLabel(String name){
        this.jLabel_b.setText(name);
    }

}
