/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import obj.DBC;
import obj.Room;
import obj.Student;

/**
 *
 * @author tungt
 */
public class StudentInfo extends javax.swing.JPanel {

    DBC dbc;
    String cur_id = "";
    BufferedImage image;
    FileInputStream fileInput;
    String path_image;
    Long fileInput_len = (long) 0;
    Boolean isChange = false;
    Student cur_student = null;
    Room room;

    void setRoom(Room room) {
        this.room = room;
    }

    void setStudent(Student student) {
        this.cur_student = student;
    }
    Student getStudent(){
        return this.cur_student;
    }
    /**
     * Creates new form StudentInfo
     */
    public StudentInfo() {
        initComponents();
        this.setSize(1100, 650);
        viewMode();
        this.setSize(1100, 650);
        try {
            image = ImageIO.read(new File("D:\\Documents\\NetBeansProjects\\SDM\\rs\\r2.png"));
        } catch (Exception e) {
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, 1100, 650, this);
    }

    void hideEdit() {
        this.move.setVisible(false);
        this.cancel.setVisible(false);
        this.edit.setVisible(false);
    }

    void resetAll() {
        isChange = false;
        this.edit.setVisible(true);
        fileInput_len = (long) 0;
        cur_student = null;
        cur_id = null;
        jTextField_add.setText("");
        jTextField_k.setText("");
        jTextField_mssv.setText("");
        jTextField_name.setText("");
        jTextField_phone.setText("");
        jTextField_school.setText("");
        jComboBox_gentl.setSelectedIndex(0);
        jFormattedTextField_birth.setText("");
        jLabel_image.setIcon(null);
    }

    void viewMode() {
        save.setVisible(false);
        move.setVisible(false);
        cancel.setVisible(false);
        jTextField_add.setEditable(false);
        jTextField_k.setEditable(false);
        jTextField_mssv.setEditable(false);
        jTextField_name.setEditable(false);
        jTextField_phone.setEditable(false);
        jTextField_room.setEditable(false);
        jTextField_school.setEditable(false);
        jComboBox_gentl.setEditable(false);
        jComboBox_gentl.setVisible(false);
        jFormattedTextField_birth.setEditable(false);
        import_image.setVisible(false);

    }

    void editMode() {

        cur_id = jTextField_mssv.getText().trim();
        save.setVisible(true);
        cancel.setVisible(true);
        move.setVisible(true);
        jTextField_add.setEditable(true);
        jTextField_k.setEditable(true);
        jTextField_mssv.setEditable(true);
        jTextField_name.setEditable(true);
        jTextField_phone.setEditable(true);
        jTextField_school.setEditable(true);
        jComboBox_gentl.setEditable(true);
        jComboBox_gentl.setVisible(true);

        jFormattedTextField_birth.setEditable(true);
        import_image.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        back = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_room = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_gentl = new javax.swing.JComboBox<>();
        jTextField_school = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField_birth = new javax.swing.JFormattedTextField();
        jLabel_image = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_k = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_mssv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_add = new javax.swing.JTextField();
        import_image = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        jTextField_gioiTinh = new javax.swing.JTextField();
        move = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();

        jFileChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jFileChooser1MousePressed(evt);
            }
        });

        setPreferredSize(new java.awt.Dimension(1100, 650));

        back.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\SDM\\rs\\back.png")); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mã số sinh viên");
        jLabel2.setOpaque(true);

        jTextField_room.setBackground(new java.awt.Color(0, 0, 204));
        jTextField_room.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_room.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_room.setCaretColor(new java.awt.Color(255, 255, 0));
        jTextField_room.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_roomKeyPressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Địa chỉ");
        jLabel6.setOpaque(true);

        jComboBox_gentl.setBackground(new java.awt.Color(0, 0, 102));
        jComboBox_gentl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox_gentl.setForeground(new java.awt.Color(0, 0, 153));
        jComboBox_gentl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Nam", " Nữ" }));
        jComboBox_gentl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_gentlItemStateChanged(evt);
            }
        });
        jComboBox_gentl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox_gentlMousePressed(evt);
            }
        });

        jTextField_school.setBackground(new java.awt.Color(0, 0, 204));
        jTextField_school.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_school.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_school.setCaretColor(new java.awt.Color(255, 255, 0));
        jTextField_school.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_schoolMousePressed(evt);
            }
        });
        jTextField_school.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_schoolKeyPressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Phòng");
        jLabel9.setOpaque(true);

        jTextField_phone.setBackground(new java.awt.Color(0, 0, 204));
        jTextField_phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_phone.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_phone.setCaretColor(new java.awt.Color(255, 255, 0));
        jTextField_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_phoneKeyPressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Viện");
        jLabel3.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tên");
        jLabel1.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(0, 0, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Số điện thoại");
        jLabel7.setOpaque(true);

        jFormattedTextField_birth.setBackground(new java.awt.Color(0, 0, 204));
        jFormattedTextField_birth.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTextField_birth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField_birth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField_birth.setCaretColor(new java.awt.Color(255, 255, 0));
        jFormattedTextField_birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_birthActionPerformed(evt);
            }
        });
        jFormattedTextField_birth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_birthKeyPressed(evt);
            }
        });

        jLabel_image.setBackground(new java.awt.Color(51, 51, 255));
        jLabel_image.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(0, 0, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ngày sinh");
        jLabel4.setOpaque(true);

        jTextField_k.setBackground(new java.awt.Color(0, 0, 204));
        jTextField_k.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_k.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_k.setCaretColor(new java.awt.Color(255, 255, 0));
        jTextField_k.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_kKeyPressed(evt);
            }
        });

        jTextField_name.setBackground(new java.awt.Color(0, 0, 204));
        jTextField_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_name.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_name.setCaretColor(new java.awt.Color(255, 255, 0));
        jTextField_name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyPressed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 204));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DD/MM/YYYY");
        jLabel10.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(0, 0, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Giới tính");
        jLabel5.setOpaque(true);

        jTextField_mssv.setBackground(new java.awt.Color(0, 0, 204));
        jTextField_mssv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_mssv.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_mssv.setCaretColor(new java.awt.Color(255, 255, 0));
        jTextField_mssv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_mssvKeyPressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Khóa");
        jLabel8.setOpaque(true);

        jTextField_add.setBackground(new java.awt.Color(0, 0, 204));
        jTextField_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_add.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_add.setCaretColor(new java.awt.Color(255, 255, 0));
        jTextField_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addActionPerformed(evt);
            }
        });
        jTextField_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_addKeyPressed(evt);
            }
        });

        import_image.setBackground(new java.awt.Color(0, 0, 204));
        import_image.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        import_image.setForeground(new java.awt.Color(255, 255, 255));
        import_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        import_image.setText("Chọn ảnh từ máy tính");
        import_image.setOpaque(true);
        import_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                import_imageMousePressed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(0, 0, 204));
        edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit.setText("Sửa thông tin");
        edit.setOpaque(true);
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editMousePressed(evt);
            }
        });

        save.setBackground(new java.awt.Color(0, 0, 204));
        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save.setText("Lưu");
        save.setOpaque(true);
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saveMousePressed(evt);
            }
        });

        jTextField_gioiTinh.setEditable(false);
        jTextField_gioiTinh.setBackground(new java.awt.Color(0, 0, 204));
        jTextField_gioiTinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_gioiTinh.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_gioiTinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_gioiTinhKeyPressed(evt);
            }
        });

        move.setBackground(new java.awt.Color(0, 51, 204));
        move.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        move.setForeground(new java.awt.Color(255, 255, 255));
        move.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        move.setText("Chuyển phòng");
        move.setOpaque(true);

        cancel.setBackground(new java.awt.Color(0, 51, 204));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("Hủy trọ");
        cancel.setOpaque(true);
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(265, 265, 265)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jTextField_room, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_school, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_add, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_k, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFormattedTextField_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_gentl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(import_image, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(move, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(222, 222, 222))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_add, jTextField_k, jTextField_mssv, jTextField_name, jTextField_phone, jTextField_room, jTextField_school});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_k, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_school, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_gentl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(import_image, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(move, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField_add, jTextField_gioiTinh, jTextField_k, jTextField_mssv, jTextField_name, jTextField_phone, jTextField_room, jTextField_school});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addActionPerformed

    private void jFormattedTextField_birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_birthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_birthActionPerformed

    private void import_imageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_import_imageMousePressed
        // TODO add your handling code here:
        isChange = true;
        jFileChooser1 = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        jFileChooser1.addChoosableFileFilter(filter);
        int i = jFileChooser1.showOpenDialog(null);
        if (i == 0) {
            try {
                InputStream ip = null;
                File fileCh = jFileChooser1.getSelectedFile();
                fileInput = new FileInputStream(fileCh);
                fileInput_len = (long) fileCh.length();
                path_image = fileCh.toString();
                ImageIcon img = new ImageIcon(path_image);
                Image temp = img.getImage();
                Image newtemp = temp.getScaledInstance(jLabel_image.getWidth(), jLabel_image.getHeight(), Image.SCALE_SMOOTH);
                img = new ImageIcon(newtemp);
                jLabel_image.setIcon(img);
            } catch (FileNotFoundException ex) {
            }
        }
    }//GEN-LAST:event_import_imageMousePressed

    private void editMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMousePressed
        // TODO add your handling code here:
        resetWhenEdit();
    }//GEN-LAST:event_editMousePressed
    void resetWhenEdit() {
        if (cur_student != null) {
            jTextField_name.setText(cur_student.getStudent_name());
            jTextField_add.setText(cur_student.getStudent_homeLand());
            jTextField_k.setText(cur_student.getStudent_k() + "");
            jTextField_mssv.setText(cur_student.getStudent_code());
            jTextField_phone.setText(cur_student.getStudent_phone());
            jTextField_school.setText(cur_student.getStudent_school());
            setImage(cur_student.getStudent_image());
            int j = 1;
            if (cur_student.getStudent_gentl().equals("Nam")) {
                j = 0;
            }
            setjComboBox(j);
            jComboBox_gentl.setVisible(false);
            jTextField_gioiTinh.setText(cur_student.getStudent_gentl());
            setjNgaySinh(cur_student.getStudent_birth());
        }
        editMode();
    }

    void doSave() {
        dbc = new DBC();
        String s = "";
        String cur_student_code = "";
        if (edit.isVisible()) {
            s = "update";
            cur_student_code = cur_student.getStudent_code();
        } else {
            cur_student_code = jTextField_mssv.getText();
        }
        dbc.exeSQL_image("", s, jTextField_mssv.getText().trim(), jTextField_name.getText().trim(),
                Integer.parseInt(jTextField_k.getText().trim()),
                jTextField_school.getText().trim(), jFormattedTextField_birth.getText(),
                jComboBox_gentl.getSelectedItem().toString().trim(), jTextField_add.getText().trim(),
                jTextField_phone.getText().trim(), room.getRoom_id(), room.getDormitory_name(),
                fileInput, fileInput_len, cur_student_code);
        fileInput_len = (long) 0;
        cur_student = dbc.getStudent(jTextField_mssv.getText());
        viewMode();
        isChange = false;
        fileInput_len = (long) 0;
    }

    void dontSave() {
        if (cur_student != null) {

            setjTextField_name(cur_student.getStudent_name());
            setjTextField_add(cur_student.getStudent_homeLand());
            setjTextField_k(cur_student.getStudent_k() + "");
            setjTextField_mssv(cur_student.getStudent_code());
            setjTextField_phone(cur_student.getStudent_phone());
            setjTextField_school(cur_student.getStudent_school());
            setImage(cur_student.getStudent_image());
            int j = 1;
            if (cur_student.getStudent_gentl().equals("Nam")) {
                j = 0;
            }
            setjComboBox(j);
            setjNgaySinh(cur_student.getStudent_birth());
            viewMode();
            isChange = false;
            fileInput_len = (long) 0;
        } else {
            resetAll();
            editMode();
            edit.setVisible(false);
            isChange = false;
            fileInput_len = (long) 0;
        }
    }
    private void saveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMousePressed
        // TODO add your handling code here:

        if (!isChange) {
            JOptionPane.showMessageDialog(this, "Bạn chưa thay đổi thông tin nào", " Thông báo", HEIGHT);
            return;
        }
        String s1;
        s1 = jTextField_name.getText();
        s1 += "a";
        s1.trim();
        s1 = s1.substring(0, s1.length());
        System.out.println(s1.isEmpty());
        System.out.println(s1);
        if (s1.equals("")) {
            JOptionPane.showMessageDialog(this, " Thông tin chưa đầy đủ", " Thông báo", HEIGHT);
            return;
        }
        int i = JOptionPane.showConfirmDialog(this, "Lưu những thay đổi?", " Lưu", WIDTH);
        if (i == 0) {
            doSave();
        }
        if (i == 1) {
            dontSave();
        }
    }//GEN-LAST:event_saveMousePressed

    private void jTextField_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyPressed
        // TODO add your handling code here:
        isChange = true;
    }//GEN-LAST:event_jTextField_nameKeyPressed

    private void jTextField_mssvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_mssvKeyPressed
        // TODO add your handling code here:
        isChange = true;
    }//GEN-LAST:event_jTextField_mssvKeyPressed

    private void jTextField_kKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_kKeyPressed
        // TODO add your handling code here:
        isChange = true;
    }//GEN-LAST:event_jTextField_kKeyPressed

    private void jTextField_schoolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_schoolMousePressed
        // TODO add your handling code here:
        isChange = true;
    }//GEN-LAST:event_jTextField_schoolMousePressed

    private void jTextField_addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_addKeyPressed
        // TODO add your handling code here:
        isChange = true;
    }//GEN-LAST:event_jTextField_addKeyPressed

    private void jTextField_schoolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_schoolKeyPressed
        // TODO add your handling code here:
        isChange = true;
    }//GEN-LAST:event_jTextField_schoolKeyPressed

    private void jTextField_phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phoneKeyPressed
        // TODO add your handling code here:
        isChange = true;
    }//GEN-LAST:event_jTextField_phoneKeyPressed

    private void jTextField_roomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_roomKeyPressed
        // TODO add your handling code here:
        isChange = true;
    }//GEN-LAST:event_jTextField_roomKeyPressed

    private void jComboBox_gentlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_gentlMousePressed
        // TODO add your handling code here:
        isChange = true;
    }//GEN-LAST:event_jComboBox_gentlMousePressed

    private void jFormattedTextField_birthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_birthKeyPressed
        // TODO add your handling code here:
        isChange = true;
    }//GEN-LAST:event_jFormattedTextField_birthKeyPressed

    private void jTextField_gioiTinhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_gioiTinhKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_gioiTinhKeyPressed

    private void jComboBox_gentlItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_gentlItemStateChanged
        // TODO add your handling code here:
        isChange = true;
        jTextField_gioiTinh.setText(jComboBox_gentl.getItemAt(jComboBox_gentl.getSelectedIndex()));
    }//GEN-LAST:event_jComboBox_gentlItemStateChanged

    private void cancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMousePressed

    private void jFileChooser1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFileChooser1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser1MousePressed
    public JLabel getCancel(){
        return cancel;
    }
    public JLabel getBack() {
        return back;
    }
    public JLabel getMove(){
        return move;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel edit;
    private javax.swing.JLabel import_image;
    private javax.swing.JComboBox<String> jComboBox_gentl;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField_birth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JTextField jTextField_add;
    private javax.swing.JTextField jTextField_gioiTinh;
    private javax.swing.JTextField jTextField_k;
    private javax.swing.JTextField jTextField_mssv;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_room;
    private javax.swing.JTextField jTextField_school;
    private javax.swing.JLabel move;
    private javax.swing.JLabel save;
    // End of variables declaration//GEN-END:variables

    public void setjTextField_add(String name) {
        this.jTextField_add.setText(" " + name);
    }

    public void setJTextfield_gioiTinh(String name) {
        this.jTextField_gioiTinh.setText(" " + name);
    }

    public void setjTextField_k(String name) {
        this.jTextField_k.setText(" " + name);
    }

    public void setjTextField_mssv(String name) {
        this.jTextField_mssv.setText(" " + name);
    }

    public void setjTextField_name(String name) {
        this.jTextField_name.setText(" " + name);
    }

    public void setjTextField_phone(String name) {
        this.jTextField_phone.setText(" " + name);
    }

    public void setjTextField_room(String name) {
        this.jTextField_room.setText(" " + name);
    }

    public void setjTextField_school(String name) {
        this.jTextField_school.setText(" " + name);
    }

    public void setjComboBox(int i) {
        this.jComboBox_gentl.setSelectedIndex(i);
    }

    public void setjNgaySinh(String name) {
        this.jFormattedTextField_birth.setText(name);
    }

    public void setImage(Blob image) {
        try {
            byte[] temp = image.getBytes(1L, (int) image.length());
            ImageIcon ik = new ImageIcon(temp);
            Image igm = ik.getImage();
            Image newimg = igm.getScaledInstance(200, 236, Image.SCALE_REPLICATE);
            ik = new ImageIcon(newimg);
            jLabel_image.setIcon(ik);

        } catch (SQLException ex) {
        }
    }
    
    public static void main(String[] args) {
        new StudentInfo().setVisible(true);
    }
}
