/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanly_sv_ktx;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
//import obj.Manager;

/**
 *
 * @author tungt
 */
public class DiagramPanel extends javax.swing.JPanel {

    private BufferedImage image;
    /**
     * Creates new form DiagramPanel
     */
    public void resetColor() {
        b6.setForeground(new java.awt.Color(51, 102, 255));
        b7.setForeground(new java.awt.Color(51, 102, 255));
        b5.setForeground(new java.awt.Color(51, 102, 255));
        b10.setForeground(new java.awt.Color(51, 102, 255));
        b13.setForeground(new java.awt.Color(51, 102, 255));
        b9.setForeground(new java.awt.Color(51, 102, 255));
        b5b.setForeground(new java.awt.Color(51, 102, 255));
        b13.setForeground(new java.awt.Color(51, 102, 255));
        b13b.setForeground(new java.awt.Color(51, 102, 255));
        b8.setForeground(new java.awt.Color(51, 102, 255));
        b7bis.setForeground(new java.awt.Color(51, 102, 255));
        b3.setForeground(new java.awt.Color(51, 102, 255));
    }

    public DiagramPanel() {
        initComponents();
        this.setSize(1100, 650);
        try {
            image = ImageIO.read(new File("src/res/g73.jpg"));
        } catch (Exception e) {
            System.out.println("can't find image");
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, 1100, 650, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_NhaDeXe = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        jLabel_clb = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        jLabel_SanTheThao = new javax.swing.JLabel();
        b7bis = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b5b = new javax.swing.JLabel();
        b13b = new javax.swing.JLabel();
        b13 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        jLabel_NhaDeXe7 = new javax.swing.JLabel();
        jLabel_NhaDeXe8 = new javax.swing.JLabel();
        jLabel_NhaDeXe9 = new javax.swing.JLabel();
        b9 = new javax.swing.JLabel();
        b10 = new javax.swing.JLabel();
        jLabel_SanTheThao1 = new javax.swing.JLabel();
        LogOut1 = new javax.swing.JLabel();
        LogOut2 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        KhuNha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 650));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jLabel_NhaDeXe.setBackground(new java.awt.Color(255, 204, 0));
        jLabel_NhaDeXe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_NhaDeXe.setForeground(new java.awt.Color(51, 102, 255));
        jLabel_NhaDeXe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_NhaDeXe.setText("Nhà Để Xe");
        jLabel_NhaDeXe.setOpaque(true);

        b6.setBackground(new java.awt.Color(255, 204, 0));
        b6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b6.setForeground(new java.awt.Color(51, 102, 255));
        b6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b6.setText("Nhà B6");
        b6.setOpaque(true);
        b6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                b6MouseMoved(evt);
            }
        });

        jLabel_clb.setBackground(new java.awt.Color(255, 204, 0));
        jLabel_clb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_clb.setForeground(new java.awt.Color(0, 102, 204));
        jLabel_clb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_clb.setText("CLB Văn Hóa");
        jLabel_clb.setOpaque(true);

        b7.setBackground(new java.awt.Color(255, 204, 0));
        b7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b7.setForeground(new java.awt.Color(51, 102, 255));
        b7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b7.setText("Nhà B7");
        b7.setOpaque(true);
        b7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                b7MouseMoved(evt);
            }
        });

        jLabel_SanTheThao.setBackground(new java.awt.Color(0, 153, 0));
        jLabel_SanTheThao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_SanTheThao.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_SanTheThao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_SanTheThao.setText("Cây xanh");
        jLabel_SanTheThao.setOpaque(true);

        b7bis.setBackground(new java.awt.Color(255, 204, 0));
        b7bis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b7bis.setForeground(new java.awt.Color(51, 102, 255));
        b7bis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b7bis.setText("Nhà B7 bis");
        b7bis.setOpaque(true);
        b7bis.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                b7bisMouseMoved(evt);
            }
        });

        b8.setBackground(new java.awt.Color(255, 204, 0));
        b8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b8.setForeground(new java.awt.Color(51, 102, 255));
        b8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b8.setText("Nhà B8");
        b8.setOpaque(true);
        b8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                b8MouseMoved(evt);
            }
        });

        b5.setBackground(new java.awt.Color(255, 204, 0));
        b5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b5.setForeground(new java.awt.Color(51, 102, 255));
        b5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b5.setText("Nhà B5");
        b5.setOpaque(true);
        b5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                b5MouseMoved(evt);
            }
        });

        b5b.setBackground(new java.awt.Color(255, 204, 0));
        b5b.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b5b.setForeground(new java.awt.Color(51, 102, 255));
        b5b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b5b.setText("Nhà B5b");
        b5b.setOpaque(true);
        b5b.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                b5bMouseMoved(evt);
            }
        });

        b13b.setBackground(new java.awt.Color(255, 204, 0));
        b13b.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b13b.setForeground(new java.awt.Color(51, 102, 255));
        b13b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b13b.setText("Nhà B13b");
        b13b.setOpaque(true);
        b13b.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                b13bMouseMoved(evt);
            }
        });

        b13.setBackground(new java.awt.Color(255, 204, 0));
        b13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b13.setForeground(new java.awt.Color(51, 102, 255));
        b13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b13.setText("Nhà B13");
        b13.setOpaque(true);
        b13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                b13MouseMoved(evt);
            }
        });

        b3.setBackground(new java.awt.Color(255, 204, 0));
        b3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(51, 102, 255));
        b3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b3.setText("Nhà B3");
        b3.setOpaque(true);
        b3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                b3MouseMoved(evt);
            }
        });

        jLabel_NhaDeXe7.setBackground(new java.awt.Color(255, 204, 0));
        jLabel_NhaDeXe7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_NhaDeXe7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel_NhaDeXe7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_NhaDeXe7.setText("Bảo Vệ");
        jLabel_NhaDeXe7.setOpaque(true);

        jLabel_NhaDeXe8.setBackground(new java.awt.Color(0, 153, 0));
        jLabel_NhaDeXe8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_NhaDeXe8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NhaDeXe8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_NhaDeXe8.setText("Sân Thể Thao");
        jLabel_NhaDeXe8.setOpaque(true);

        jLabel_NhaDeXe9.setBackground(new java.awt.Color(0, 153, 0));
        jLabel_NhaDeXe9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_NhaDeXe9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NhaDeXe9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_NhaDeXe9.setText("Sân Thể Thao");
        jLabel_NhaDeXe9.setOpaque(true);

        b9.setBackground(new java.awt.Color(255, 204, 0));
        b9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b9.setForeground(new java.awt.Color(51, 102, 255));
        b9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b9.setText("<html>TTQL-KTX<br>    Nhà B9</html>");
        b9.setOpaque(true);
        b9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                b9MouseMoved(evt);
            }
        });

        b10.setBackground(new java.awt.Color(255, 204, 0));
        b10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b10.setForeground(new java.awt.Color(51, 102, 255));
        b10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b10.setText("Nhà B10");
        b10.setOpaque(true);
        b10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                b10MouseMoved(evt);
            }
        });

        jLabel_SanTheThao1.setBackground(new java.awt.Color(0, 153, 0));
        jLabel_SanTheThao1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_SanTheThao1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_SanTheThao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_SanTheThao1.setText("Sân Thể Thao");
        jLabel_SanTheThao1.setOpaque(true);

        LogOut1.setBackground(new java.awt.Color(0, 0, 255));
        LogOut1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LogOut1.setForeground(new java.awt.Color(255, 255, 255));
        LogOut1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LogOut1.setText("Quản lý: ");
        LogOut1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogOut1.setOpaque(true);

        LogOut2.setBackground(new java.awt.Color(0, 0, 255));
        LogOut2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LogOut2.setForeground(new java.awt.Color(255, 255, 255));
        LogOut2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LogOut2.setText("Số nhà: ");
        LogOut2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogOut2.setOpaque(true);

        Name.setBackground(new java.awt.Color(0, 0, 255));
        Name.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Name.setText("Admin");
        Name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Name.setOpaque(true);

        KhuNha.setBackground(new java.awt.Color(0, 0, 255));
        KhuNha.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        KhuNha.setForeground(new java.awt.Color(255, 255, 255));
        KhuNha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        KhuNha.setText("Cả KTX");
        KhuNha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        KhuNha.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_SanTheThao1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7bis, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b6)
                        .addComponent(jLabel_NhaDeXe, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_clb, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5b, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_SanTheThao)
                            .addComponent(b9)
                            .addComponent(jLabel_NhaDeXe9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b13b, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_NhaDeXe8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LogOut2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(KhuNha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel_NhaDeXe7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {b10, b13, b13b, b3, b5, b5b, b6, b7, b7bis, b8, b9, jLabel_NhaDeXe, jLabel_NhaDeXe8, jLabel_NhaDeXe9, jLabel_SanTheThao, jLabel_SanTheThao1, jLabel_clb});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_NhaDeXe, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b13b, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(b5b, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b6)
                                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LogOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LogOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KhuNha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_NhaDeXe8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_clb)
                        .addGap(18, 18, 18)
                        .addComponent(b7)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel_SanTheThao1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b7bis)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_SanTheThao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel_NhaDeXe9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b8)
                    .addComponent(jLabel_NhaDeXe7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {b6, b7, b7bis, b8, jLabel_NhaDeXe, jLabel_clb});

    }// </editor-fold>//GEN-END:initComponents

    private void b6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseMoved
        b6.setForeground(Color.red);
    }//GEN-LAST:event_b6MouseMoved

    private void b7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseMoved
        b7.setForeground(Color.red);
    }//GEN-LAST:event_b7MouseMoved

    private void b7bisMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7bisMouseMoved
        b7bis.setForeground(Color.red);
    }//GEN-LAST:event_b7bisMouseMoved

    private void b8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseMoved
        b8.setForeground(Color.red);
    }//GEN-LAST:event_b8MouseMoved

    private void b5bMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5bMouseMoved
        b5b.setForeground(Color.red);
    }//GEN-LAST:event_b5bMouseMoved

    private void b5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseMoved
        b5.setForeground(Color.red);
    }//GEN-LAST:event_b5MouseMoved

    private void b9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseMoved
        b9.setForeground(Color.red);
    }//GEN-LAST:event_b9MouseMoved

    private void b13bMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b13bMouseMoved
        b13b.setForeground(Color.red);
    }//GEN-LAST:event_b13bMouseMoved

    private void b13MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b13MouseMoved
        b13.setForeground(Color.red);
    }//GEN-LAST:event_b13MouseMoved

    private void b3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseMoved
        b3.setForeground(Color.red);
    }//GEN-LAST:event_b3MouseMoved

    private void b10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b10MouseMoved
        b10.setForeground(Color.red);
    }//GEN-LAST:event_b10MouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        resetColor();
    }//GEN-LAST:event_formMouseMoved

    public JLabel getB7() {
        return b7;
    }
    public JLabel getB5() {
        return b5;
    }
    public JLabel getB9() {
        return b9;
    }
    public JLabel getB7bis() {
        return b7bis;
    }
    public JLabel getB6() {
        return b6;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KhuNha;
    private javax.swing.JLabel LogOut1;
    private javax.swing.JLabel LogOut2;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel b10;
    private javax.swing.JLabel b13;
    private javax.swing.JLabel b13b;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b5b;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b7bis;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private javax.swing.JLabel jLabel_NhaDeXe;
    private javax.swing.JLabel jLabel_NhaDeXe7;
    private javax.swing.JLabel jLabel_NhaDeXe8;
    private javax.swing.JLabel jLabel_NhaDeXe9;
    private javax.swing.JLabel jLabel_SanTheThao;
    private javax.swing.JLabel jLabel_SanTheThao1;
    private javax.swing.JLabel jLabel_clb;
    // End of variables declaration//GEN-END:variables
}
