/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanly_sv_ktx;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 *
 * @author AnhTu
 */
public class MainWindow extends javax.swing.JFrame {

    private String quyenQuanLyToaNha = null;
    public boolean loginThanhCong = false;
    
    private LoginFrame lf = new LoginFrame();
    private SinhVienFrame svf;
    private PhongTroFrame ptf;
    private SinhVienFrameTheoToaNha svfTheoToaNha;
    private ToaNhaFrame tnf;
    private DoiMKFrame dmkf;
    private MainDiagram mainDia;
    
    public boolean isDangXuat = true; //nếu isDangXuat = true thì ko hiển thị đc dssv
    private boolean isDaChonMIQuanLySinhVien; //nếu đã chọn 1 miQuanLySinhVien của menu quản lý thì isDaChonMIQuanLySinhVien = true
    private boolean isDaChonMIQuanLyPhongTro;
    private boolean isDaChonMIQuanLyToaNha;
    
    public void setQuyenQuanLyToaNha(String quyenQuanLyToaNha) {
        this.quyenQuanLyToaNha = quyenQuanLyToaNha;
    }
    
    
    public MainWindow() {
        initComponents();
        setEnableQuanLy(false);
    }
    
    public void setEnableQuanLy(boolean b) {
        jMenu2.setVisible(b);
//        miQuanLySinhVien.setVisible(b);
//        miQuanLyPhongTro.setVisible(b);
//        miQuanLyToaNha.setVisible(b);
        miDangXuat.setVisible(b);
        jMenuItem3.setVisible(b);
    }
    
    public void setEnableMiSoDoKTX(boolean b) {
        miSoDoKTX.setVisible(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miDangNhap = new javax.swing.JMenuItem();
        miDangXuat = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miQuanLySinhVien = new javax.swing.JMenuItem();
        miQuanLyPhongTro = new javax.swing.JMenuItem();
        miQuanLyToaNha = new javax.swing.JMenuItem();
        miSoDoKTX = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        miContact = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("TRƯỜNG ĐẠI HỌC BÁCH KHOA HÀ NỘI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("VIỆN ĐIỆN TỬ - VIỄN THÔNG");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("HỆ THỐNG QUẢN LÝ SINH VIÊN Ở KÝ TÚC XÁ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("NHÓM 2");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/set.JPG"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bkhn.JPG"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jMenu1.setText("Hệ thống");

        miDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        miDangNhap.setText("Đăng nhập");
        miDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDangNhapActionPerformed(evt);
            }
        });
        jMenu1.add(miDangNhap);

        miDangXuat.setText("Đăng xuất");
        miDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(miDangXuat);

        jMenuItem3.setText("Đổi mật khẩu");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Thoát chương trình");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        miQuanLySinhVien.setText("Quản lý sinh viên");
        miQuanLySinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQuanLySinhVienActionPerformed(evt);
            }
        });
        jMenu2.add(miQuanLySinhVien);

        miQuanLyPhongTro.setText("Quản lý phòng trọ");
        miQuanLyPhongTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQuanLyPhongTroActionPerformed(evt);
            }
        });
        jMenu2.add(miQuanLyPhongTro);

        miQuanLyToaNha.setText("Quản lý tòa nhà");
        miQuanLyToaNha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQuanLyToaNhaActionPerformed(evt);
            }
        });
        jMenu2.add(miQuanLyToaNha);

        miSoDoKTX.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        miSoDoKTX.setText("Sơ đồ kí túc xá");
        miSoDoKTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSoDoKTXActionPerformed(evt);
            }
        });
        jMenu2.add(miSoDoKTX);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");

        jMenuItem1.setText("About project");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        miContact.setForeground(new java.awt.Color(51, 102, 255));
        miContact.setText("Contact with me");
        miContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miContactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miContactMouseExited(evt);
            }
        });
        miContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miContactActionPerformed(evt);
            }
        });
        jMenu3.add(miContact);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(47, 47, 47))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miQuanLySinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQuanLySinhVienActionPerformed
        isDaChonMIQuanLySinhVien = true;
        //thực ra có thể bỏ try catch đi vì khi chưa đăng nhập thi 4 menuItem ko hiện lên, do đó muốn bấm cũng ko đc
        try {
        //nếu đã đăng nhập rồi thì thực hiện như sau
            if (isDangXuat == false) {
                //quyenQuanLyToaNha = lf.getToaNhaDuocPhepQuanLy(); //ko cần hàm này nữa vì sau khi login xong sẽ tạo 1 cái frame MainWindow mới có quyenQuanLyToaNha đã đc thiết lập sẵn rồi. chi tiết xem loginFrame phần btOK
                if (quyenQuanLyToaNha.equals("all")) { //chú ý nếu dùng if (quyenQuanLyToaNha == "all") là sai vì quyenQuanLyToaNha != "all" luôn luôn xảy ra
                    svf = new SinhVienFrame();
                    svf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    svf.setVisible(true); //hiển thị frame sv
                    System.out.println("Đang quản lý tất cả sv");
                } else {
                    svfTheoToaNha = new SinhVienFrameTheoToaNha(quyenQuanLyToaNha);
                    svfTheoToaNha.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    svfTheoToaNha.setVisible(true);
                    System.out.println("Hiển thị dssv ở tòa nhà " + svfTheoToaNha.getTenToaNha());
                }
                //nếu dùng hàm: svf.setTenToaNha(quyenQuanLyToaNha); thì lại ko đc. vì bản thân hàm SinhVienFrameTheoToaNha() đã có hàm showDataInTable()
                //do đó khi gọi nó, hàm showDataInTable() đc gọi luôn nên tenToaNha = null ko đổi. khi ta thực hiện lệnh svf.setTenToaNha(quyenQuanLyToaNha) 
                //thì nó thực hiện sau lệnh gọi hàm showDataInTable(), nên hàm showDataInTable() sẽ lấy giá trị tenToaNha trước đó và = null

            }
        } catch (Exception e) {
            //ngoại lệ này xảy ra khi chưa đăng nhập mà ấn vào Quản lý sinh viên
            JOptionPane.showMessageDialog(null, "Bạn chưa đăng nhập!", "Lỗi!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miQuanLySinhVienActionPerformed

    private void miDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDangNhapActionPerformed
        if (isDangXuat == true) {
            setVisible(false);
            isDangXuat = false;
            lf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            lf.clearTF();
            lf.setVisible(true);

            if (lf.getToaNhaDuocPhepQuanLy() != null) {
                setEnableQuanLy(true);
                System.out.println("setEnableQuanLy(true)");
            }
        } else JOptionPane.showMessageDialog(null, "Bạn phải đăng xuất trước mới đăng nhập lại đc!", "Chú ý", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_miDangNhapActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thoát?", "Chú ý", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION)  System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void miDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDangXuatActionPerformed
        isDangXuat = true;
        if (quyenQuanLyToaNha.equals("all")) {
            if(isDaChonMIQuanLySinhVien) 
                svf.setVisible(false);
        }
        else {
            if(isDaChonMIQuanLySinhVien)
                svfTheoToaNha.setVisible(false);
        } 
        //CHÚ Ý:nếu có lệnh if lồng nhau thì phải đặt trong { } nếu ko sẽ ko thực hiện đc
        
        if(isDaChonMIQuanLyPhongTro) ptf.setVisible(false);
        if(isDaChonMIQuanLyToaNha) tnf.setVisible(false);
        setEnableQuanLy(false);
        miDangXuat.setEnabled(false);
        quyenQuanLyToaNha = null;
        System.out.println("Đã đăng xuất");
    }//GEN-LAST:event_miDangXuatActionPerformed

    private void miQuanLyPhongTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQuanLyPhongTroActionPerformed
        isDaChonMIQuanLyPhongTro = true;
        ptf = new PhongTroFrame();
        ptf.setVisible(true);
    }//GEN-LAST:event_miQuanLyPhongTroActionPerformed

    private void miQuanLyToaNhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQuanLyToaNhaActionPerformed
        isDaChonMIQuanLyToaNha = true;
        tnf = new ToaNhaFrame();
        tnf.setVisible(true);
    }//GEN-LAST:event_miQuanLyToaNhaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null, "Sản phẩm của nhóm 2, Lập trình nâng cao 20161", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void miContactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miContactMouseEntered
        miContact.setForeground(new Color(255, 51, 102));
    }//GEN-LAST:event_miContactMouseEntered

    private void miContactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miContactMouseExited
        miContact.setForeground(new Color(51, 102, 255));
    }//GEN-LAST:event_miContactMouseExited

    private void miContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miContactActionPerformed
        //mở trang facebook của t :v
        String url = "www.facebook.com/taanhtu95";
        int choice = JOptionPane.showConfirmDialog(null, "Bạn có muốn mở trình duyệt web?");
        if(choice == JOptionPane.YES_OPTION) {
            try {
                Desktop.getDesktop().browse(URI.create(url));
            } catch (IOException ex) {
                Logger.getLogger(SinhVienFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Ko thể kết nối đc!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_miContactActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        JOptionPane.showMessageDialog(null, "Đây là logo trường ĐHBK HN", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        JOptionPane.showMessageDialog(null, "Đây là logo viện ĐTVT ĐHBK HN", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        dmkf = new DoiMKFrame();
        dmkf.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void miSoDoKTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSoDoKTXActionPerformed
        mainDia = new MainDiagram();
        mainDia.setVisible(true);
        mainDia.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_miSoDoKTXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                ///////////phần code sau chỉnh sửa giao diện giống với hệ điều hành đang dùng
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                ////////////////////////////////////////////////////////////////////////////
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem miContact;
    private javax.swing.JMenuItem miDangNhap;
    private javax.swing.JMenuItem miDangXuat;
    private javax.swing.JMenuItem miQuanLyPhongTro;
    private javax.swing.JMenuItem miQuanLySinhVien;
    private javax.swing.JMenuItem miQuanLyToaNha;
    private javax.swing.JMenuItem miSoDoKTX;
    // End of variables declaration//GEN-END:variables
}
