/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dragdrop;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author AnhTu
 */
public class ComboBoxDemo extends javax.swing.JFrame {
    private DefaultComboBoxModel model;

    /**
     * Creates new form ComboBoxDemo
     */
    public ComboBoxDemo() {
        initComponents();
        initCB();
    }
    
    private void initCB() {
        model = new DefaultComboBoxModel();
        model.addElement("Hà Nội");
        model.addElement("Hải phòng");
        model.addElement("Đà Nắng");
        model.addElement("Hochiminh City");
        
        cbname.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cbname = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbmienbac = new javax.swing.JCheckBox();
        cbmiennam = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbnameItemStateChanged(evt);
            }
        });
        cbname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnameActionPerformed(evt);
            }
        });

        jLabel1.setText("Tỉnh/thành phố");

        buttonGroup1.add(cbmienbac);
        cbmienbac.setText("Miền Bắc");
        cbmienbac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmienbacActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbmiennam);
        cbmiennam.setText("Miền Nam");
        cbmiennam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmiennamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbmiennam)
                    .addComponent(cbmienbac)
                    .addComponent(cbname, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(cbmienbac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbmiennam)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnameActionPerformed
        
    }//GEN-LAST:event_cbnameActionPerformed

    private void cbmienbacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmienbacActionPerformed
        // TODO add your handling code here:
        model = new DefaultComboBoxModel();
        model.addElement("Hà Nội");
        model.addElement("Hải phòng");
        
        cbname.setModel(model);
    }//GEN-LAST:event_cbmienbacActionPerformed

    private void cbmiennamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmiennamActionPerformed
        // TODO add your handling code here:
        model = new DefaultComboBoxModel();
        model.addElement("Đà Nắng");
        model.addElement("Hochiminh City");
        
        cbname.setModel(model);
    }//GEN-LAST:event_cbmiennamActionPerformed

    private void cbnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbnameItemStateChanged
        if(evt.getStateChange()== ItemEvent.SELECTED) JOptionPane.showMessageDialog(null, "mày vừa chọn "+evt.getItem(), "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cbnameItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboBoxDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboBoxDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboBoxDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBoxDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBoxDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbmienbac;
    private javax.swing.JCheckBox cbmiennam;
    private javax.swing.JComboBox<String> cbname;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
