/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dragdrop;

import javax.swing.JOptionPane;

/**
 *
 * @author AnhTu
 */
public class RadioButtonDemo extends javax.swing.JFrame {

    /**
     * Creates new form RadioButtonDemo
     */
    public RadioButtonDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdvn = new javax.swing.JRadioButton();
        rdthai = new javax.swing.JRadioButton();
        rdanh = new javax.swing.JRadioButton();
        btnsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rdvn);
        rdvn.setText("Việt Nam");
        rdvn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdvnActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdthai);
        rdthai.setText("Thailand");

        buttonGroup1.add(rdanh);
        rdanh.setText("England");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsave)
                    .addComponent(rdvn)
                    .addComponent(rdanh)
                    .addComponent(rdthai))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(rdvn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdthai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdanh)
                .addGap(18, 18, 18)
                .addComponent(btnsave)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        if(rdvn.isSelected()) {
            int click = JOptionPane.showConfirmDialog(null, "Mày có chắc muốn chọn "+rdvn.getText(),"Chú ý!", JOptionPane.YES_NO_CANCEL_OPTION);
            switch(click) {
                case JOptionPane.YES_OPTION : JOptionPane.showMessageDialog(null, "mày vừa chọn "+rdvn.getText()); break;
                case JOptionPane.NO_OPTION : JOptionPane.showMessageDialog(null, "mày ko muốn cái ý"); break;
                case JOptionPane.CLOSED_OPTION : JOptionPane.showMessageDialog(null, "mày muốn thoát"); break;
                
            }
        }
        
        else if(rdthai.isSelected()) {
            int click = JOptionPane.showConfirmDialog(null, "Mày có chắc muốn chọn "+rdthai.getText(), "Chú ý!", JOptionPane.YES_NO_CANCEL_OPTION);
            switch(click) {
                case JOptionPane.YES_OPTION : JOptionPane.showMessageDialog(null, "mày vừa chọn "+rdthai.getText()); break;
                case JOptionPane.NO_OPTION : JOptionPane.showMessageDialog(null, "mày ko muốn cái ý"); break;
                case JOptionPane.CLOSED_OPTION : JOptionPane.showMessageDialog(null, "mày muốn thoát"); break;
                
            }
        }
        
        else if(rdanh.isSelected()) {
            int click = JOptionPane.showConfirmDialog(null, "Mày có chắc muốn chọn "+rdanh.getText(), "Chú ý!", JOptionPane.YES_NO_CANCEL_OPTION);
            switch(click) {
                case JOptionPane.YES_OPTION : JOptionPane.showMessageDialog(null, "mày vừa chọn "+rdanh.getText()); break;
                case JOptionPane.NO_OPTION : JOptionPane.showMessageDialog(null, "mày ko muốn cái ý"); break;
                case JOptionPane.CLOSED_OPTION : JOptionPane.showMessageDialog(null, "mày muốn thoát"); break;
                
            }
        }
        else JOptionPane.showMessageDialog(null, "mày đéo chọn cái gì à?","Ngu vl!",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnsaveActionPerformed

    private void rdvnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdvnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdvnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButtonDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButtonDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButtonDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButtonDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButtonDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rdanh;
    private javax.swing.JRadioButton rdthai;
    private javax.swing.JRadioButton rdvn;
    // End of variables declaration//GEN-END:variables
}
